
import React from 'react';
import type { GeneratedProfile } from '../types';
import Logo from './Logo';

interface ProfilePageProps {
  student: GeneratedProfile;
}

const ProfilePage: React.FC<ProfilePageProps> = ({ student }) => {
  return (
    <div className="bg-white" style={{ width: '210mm', height: '297mm', display: 'flex', flexDirection: 'column' }}>
      <header className="px-16 pt-12 pb-8 flex justify-between items-start bg-blue-50 border-b-4 border-blue-500">
        <div>
            <h2 className="text-5xl font-bold text-gray-800">{student.name}</h2>
            <p className="text-xl text-gray-600 mt-2">{student.age} years old • {student.center}</p>
        </div>
        <Logo className="h-16 w-auto" />
      </header>
      
      <main className="flex-grow flex p-16 space-x-12">
        <div className="w-1/3 flex-shrink-0">
          <img src={student.photo} alt={student.name} className="w-full rounded-lg shadow-xl object-cover" style={{ aspectRatio: '1 / 1' }} />
          <div className="mt-8">
            <h3 className="text-2xl font-semibold text-blue-700 border-b-2 border-blue-200 pb-2">Training Details</h3>
            <ul className="mt-4 space-y-2 text-gray-700">
                <li className="flex"><strong className="w-28 font-medium">Trade:</strong><span>{student.trade}</span></li>
                <li className="flex"><strong className="w-28 font-medium">Duration:</strong><span>{student.trainingduration}</span></li>
                <li className="flex"><strong className="w-28 font-medium">Fees:</strong><span>{student.trainingfees}</span></li>
                <li className="flex"><strong className="w-28 font-medium">Education:</strong><span>{student.education}</span></li>
            </ul>
          </div>
        </div>
        
        <div className="w-2/3">
            <h3 className="text-2xl font-semibold text-blue-700 border-b-2 border-blue-200 pb-2">Profile Narrative</h3>
            <p className="text-lg text-gray-800 mt-4 leading-relaxed whitespace-pre-wrap font-serif">
                {student.profileText}
            </p>

            <div className="mt-8">
              <h3 className="text-2xl font-semibold text-blue-700 border-b-2 border-blue-200 pb-2">Background</h3>
               <ul className="mt-4 space-y-2 text-gray-700">
                <li className="flex"><strong className="w-48 font-medium">Birthdate:</strong><span>{student.birthdate}</span></li>
                <li className="flex"><strong className="w-48 font-medium">Address:</strong><span>{student.address}</span></li>
                <li className="flex"><strong className="w-48 font-medium">Socio-Economic Status:</strong><span>{student.socioeconomicstatus}</span></li>
                <li className="flex items-start pt-2"><strong className="w-48 font-medium flex-shrink-0">Family Background:</strong><span className="italic text-gray-600">{student.familybackground}</span></li>
              </ul>
            </div>
        </div>
      </main>

      <footer className="px-16 py-6 text-center text-sm text-gray-500 bg-gray-50 border-t">
        Generated by Sarjan Foundation Student Profiler • Empowering Futures
      </footer>
    </div>
  );
};

export default ProfilePage;